# Generated by Django 4.0.3 on 2022-03-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('song', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=100)),
                ('genre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('genre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
