# Generated by Django 4.0.3 on 2022-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='genre',
        ),
    ]
