# Generated by Django 4.0.3 on 2022-03-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_remove_artist_genre_remove_rating_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bla', models.CharField(max_length=100)),
            ],
        ),
    ]
